version: "3"

services:
  janus:
    build: .
    ports:
      - 8088:8088
      - 8188:8188
#    volumes:
#      - ./configs:/opt/janus/etc/janus/

  demo:
    build: demo
    ports:
      - 2002:3000
    depends_on:
      - janus
