version: "3"

services:
  janus:
    build: .
    ports:
      - 8088:8088
      - 8188:8188
      - 7088:7088
    volumes:
      - ./conf/:/opt/janus/etc/janus/

  demo:
    build: demo
    ports:
      - 2002:3000
    depends_on:
      - janus
  nginx:
    image: nginx:alpine
    ports:
      - 3001:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - demo

